# to my knowledge, configuration properties of all the project!
# it's like a control panel

#spring.application.name=firstproject
#modify to 8080
#server.port=8080
#server.port=8081
#spring.datasource.url=jdbc:mysql://127.0.0.1/ProjectGadgets
#spring.datasource.username=root
#spring.datasource.password=

#create, if exist = update
#spring.jpa.hibernate.ddl-auto=update

#identifying the dialect of the DB, btw its local in XAMPP
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# I don't use spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver cause
# springboot recognize to where I want to connect with pom.xml and jdbc:mysql in the url

# I want to see the queries to tho DB in the console
#spring.jpa.show-sql=true

spring.application.name=firstproject
server.port=8080

# ==========================================
# CONEXIÓN A SUPABASE (POSTGRESQL)
# ==========================================
# Cambiamos jdbc:mysql por jdbc:postgresql y ponemos tu host de Supabase
spring.datasource.url=jdbc:postgresql://db.ffvsbnaeqovurgpfrssd.supabase.co:5432/postgres
spring.datasource.username=postgres
# Reemplaza esto con la contraseña real que le asignaste a tu base de datos
spring.datasource.password=ajvpl11938418

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update

# Identificando el nuevo dialecto de la DB (PostgreSQL)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostrar los queries en la consola
spring.jpa.show-sql=true



